### ISSUE TITLE
Images from two different cameras save as the same name

### ISSUE THREAD

**Issue by Amersel** [DIYBookScanner/spreads#230]
When I was using spreads, after scanning a couple pages as a test and saving them, I saw that there were only a half of the pages I scanned listed in the raw directory. 

After a bit of frustration, I tried `spread --verbose wizard asdf` and it showed that for each scan, _the photos were saved as the same filename_, overwriting the original image from the odd camera.

```
Found 2 devices!
Setting up devices for capturing.
Workflow: Preparing capture.
Workflow: Preparing capture in devices
Workflow: Running 'prepare_capture' hooks
Workflow: Running 'start_trigger_loop' hooks
( /b) capture | (r) retake last shot | (f) finish 
Workflow: Triggering capture.
Workflow: Sending capture command to devices
root: File added.
GPhoto2Camera[odd]: Setting EXIF orientation on captured image
root: File added.
GPhoto2Camera[odd]: Setting EXIF orientation on captured image
Workflow: Running 'capture' hooks
bagit: Adding path asdf/data/raw/003.jpg to payload
bagit: Adding path asdf/pagemeta.json to payload
bagit: Adding path asdf/data/raw/003.jpg to payload
Shot   6 pages [991333/h] bagit: Adding path /home/antonizoon/asdf/bag-info.txt to payload
```

I've already configured which camera is odd and even, and tested both cameras to work... In addition, I have tested `--no-parallel-capture` and it proves that the original Odd image exists and is thus overwritten by the even image with the same filename. How do I remedy this issue?

Config.yaml:

```
device:
    upside_down: no
    parallel_capture: yes
    flip_target_pages: no
    focus_mode: autofocus_all
    target_page:
        None: even
        '000030244763': even
        '3085055': odd
```
